/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.23
 * Generated at: 2016-09-19 01:54:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class first_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/E:/cricketshop/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/cricket/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153410282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1473828546682L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("\t\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write(" \t\t");
      if (_jspx_meth_c_005fimport_005f0(_jspx_page_context))
        return;
      out.write("\t\r\n");
      out.write(" \t\r\n");
      out.write(" </head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write(" \t\t");
      if (_jspx_meth_c_005fimport_005f1(_jspx_page_context))
        return;
      out.write("\t\r\n");
      out.write(" \t\t\r\n");
      out.write(" <header>\r\n");
      out.write("<header id=\"v1\">\r\n");
      out.write("<a href=\"/https://www.facebook.com/?stype=lo&jlou=AfexEBeNNwzkc7Tx6rqWH6bdyyCvMhTW657AG7SUFCgRlEUSAV6FR6S1beMO91658JgTjBug0PhoWqgA0E5anuM21mOVVbYEjbM498g3c2etPw&smuh=1939&lh=Ac_GgFXjPIisaFGp\">\r\n");
      out.write("<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/fb.png\" alt=\"...\"width=\"70\" height=\"70\"/>\r\n");
      out.write(" </a>\r\n");
      out.write(" <a href=\"https://twitter.com/?lang=en\">\r\n");
      out.write("<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/twitter.jpg\" alt=\"...\"width=\"70\" height=\"70\"/> </a>\r\n");
      out.write(" <a href=\"https://www.youtube.com/?gl=IN\">\r\n");
      out.write("<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/youtube.png\" alt=\"...\"width=\"70\" height=\"70\"/> </a>\r\n");
      out.write(" <a href=\"https://in.linkedin.com/\">\r\n");
      out.write("<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/linked.png\" alt=\"...\"width=\"70\" height=\"70\"/>\r\n");
      out.write(" </a>\r\n");
      out.write(" </header>\r\n");
      out.write(" <header id=\"v2\">\r\n");
      out.write("<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/logo.png\" alt=\"...\"> </header>\r\n");
      out.write(" <header id=\"v3\">\r\n");
      out.write(" <h1>Cric Bazaar</h1>\r\n");
      out.write(" <p>Live The Game</p>\r\n");
      out.write(" </header>\r\n");
      out.write("</header>\r\n");
      out.write("<div class=\"nav_bar\">\r\n");
      out.write(" <a href=\"first.html\">Home</a>&nbsp;&nbsp;|\r\n");
      out.write(" <a href=\"register.html\">RegisterHere</a>&nbsp;&nbsp;|\r\n");
      out.write(" <a href=\"login.html\">Login</a>&nbsp;&nbsp;|\r\n");
      out.write(" <a href=\"#\">Current Offers</a>&nbsp;&nbsp;|\r\n");
      out.write(" <a href=\"aboutus.html\">About us</a>&nbsp;&nbsp;|\r\n");
      out.write(" <a href=\"contactus.html\">Contact us</a>&nbsp;&nbsp;\r\n");
      out.write(" </div>\r\n");
      out.write(" <div id=\"carousel1\" class=\"carousel slide\" data-ride=\"carousel\">\r\n");
      out.write("   <ol class=\"carousel-indicators\">\r\n");
      out.write("     <li data-target=\"#carousel1\" data-slide-to=\"0\" class=\"active\"></li>\r\n");
      out.write("     <li data-target=\"#carousel1\" data-slide-to=\"1\"></li>\r\n");
      out.write("     <li data-target=\"#carousel1\" data-slide-to=\"2\"></li>\r\n");
      out.write("   </ol>\r\n");
      out.write("   <div class=\"carousel-inner\" role=\"listbox\">\r\n");
      out.write("     <div class=\"item active\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/ca1.png\" alt=\"First slide image\" class=\"center-block\">\r\n");
      out.write("       <div class=\"carousel-caption\">\r\n");
      out.write("         <h3>First slide Heading</h3>\r\n");
      out.write("         <p>First slide Caption</p>\r\n");
      out.write("       </div>\r\n");
      out.write("     </div>\r\n");
      out.write("     <div class=\"item\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/ca2.png\" alt=\"Second slide image\" class=\"center-block\">\r\n");
      out.write("       <div class=\"carousel-caption\">\r\n");
      out.write("         <h3>Second slide Heading</h3>\r\n");
      out.write("         <p>Second slide Caption</p>\r\n");
      out.write("       </div>\r\n");
      out.write("     </div>\r\n");
      out.write("     <div class=\"item\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/ca3.png\" alt=\"Third slide image\" class=\"center-block\">\r\n");
      out.write("       <div class=\"carousel-caption\">\r\n");
      out.write("         <h3>Third slide Heading</h3>\r\n");
      out.write("         <p>Third slide Caption</p>\r\n");
      out.write("       </div>\r\n");
      out.write("     </div>\r\n");
      out.write("   </div>\r\n");
      out.write("   <a class=\"left carousel-control\" href=\"#carousel1\" role=\"button\" data-slide=\"prev\"><span class=\"glyphicon glyphicon-chevron-left\" aria-hidden=\"true\"></span><span class=\"sr-only\">Previous</span></a><a class=\"right carousel-control\" href=\"#carousel1\" role=\"button\" data-slide=\"next\"><span class=\"glyphicon glyphicon-chevron-right\" aria-hidden=\"true\"></span><span class=\"sr-only\">Next</span></a></div>\r\n");
      out.write("\r\n");
      out.write(" <div id=\"border\">\r\n");
      out.write(" \r\n");
      out.write(" <h2> featured products</h2>\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" </div>\r\n");
      out.write(" \r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" <div class=\"col-md-4\">\r\n");
      out.write(" <p> <i> <strong> <a href=\"bat.jpg\" align= right>bats</a>  </strong>  </i> </p>\r\n");
      out.write(" <img class=\"img-responsive\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/bat.jpg\" alt=\"strwpie\" width=\"170\" height=\"170\" hspace=\"30\" />\r\n");
      out.write(" <p>A cricket bat is a specialised piece of equipment used by batsmen in the sport of cricket to hit the ball, typically consisting of a cane handle attached to a flat-fronted willow-wood blade.</p>\r\n");
      out.write(" \r\n");
      out.write(" </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   <div class=\"col-md-4\">\r\n");
      out.write("   <p> <i> <strong> <a href=\"html_images.asp\" align= center>balls </a> </strong>  </i> </p>\r\n");
      out.write("<img class=\"img-responsive\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/ball.jpg\" alt=\"cupcc\" width=\"170\" height=\"170\"  hspace=\"20\"/>\r\n");
      out.write("<p>A cricket ball is a hard, solid ball used to play cricket. A cricket ball consists of cork covered by leather, and manufacture is regulated by cricket law at first class level.The manipulation of a cricket ball, through employment of its various physical properties, is a staple component of bowling and dismissing batsmenMovement in the air, and off the ground, is influenced by the condition of the ball, the efforts of the bowler .</p>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"col-md-4\">\r\n");
      out.write(" <p> <i> <strong> <a href=\"bat.jpg\" align= right>stumps</a>  </strong>  </i> </p>\r\n");
      out.write(" <img class=\"img-responsive\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/stumps.png\" alt=\"strwpie\" width=\"170\" height=\"170\" hspace=\"30\"/>\r\n");
      out.write(" <p>In cricket, the stumps are the three vertical posts that support the \"bails\" and form the wicket. Stumping or being stumped is a method of dismissing a batsmanThe overall width of each wicket is 9 inches (22.9 cm). Each stump is 28 inches (71.1 cm) tall with maximum and minimum diameters of 11â2 inches (3.81 cm) and 13â8 inches (3.49 cm). They have a spike at one end for inserting into the ground, and the other end has a U-shaped 'through groove' to provide a resting place for the bails..</p>\r\n");
      out.write(" \r\n");
      out.write(" </div>\r\n");
      out.write(" \r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<footer class=\"f7\">\r\n");
      out.write("  <p>Posted by: S.M.Vignesh Kumar</p>\r\n");
      out.write("  <p>Contact information: <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/mailto:vigneshkumar@gmail.com\">vigneshkumar@gmail.com</a></p>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fimport_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f0 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    _jspx_th_c_005fimport_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fimport_005f0.setParent(null);
    // /WEB-INF/views/first.jsp(10,3) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fimport_005f0.setUrl("/head-meta");
    int[] _jspx_push_body_count_c_005fimport_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fimport_005f0 = _jspx_th_c_005fimport_005f0.doStartTag();
      if (_jspx_th_c_005fimport_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fimport_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fimport_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fimport_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fimport_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f1 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    _jspx_th_c_005fimport_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fimport_005f1.setParent(null);
    // /WEB-INF/views/first.jsp(15,3) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fimport_005f1.setUrl("/head");
    int[] _jspx_push_body_count_c_005fimport_005f1 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fimport_005f1 = _jspx_th_c_005fimport_005f1.doStartTag();
      if (_jspx_th_c_005fimport_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fimport_005f1[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fimport_005f1.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fimport_005f1.doFinally();
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f1);
    }
    return false;
  }
}
