/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.23
 * Generated at: 2016-09-19 12:45:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class head_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/E:/cricketshop/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/cricket/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153410282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1473828546682L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("#v1\r\n");
      out.write("{\r\n");
      out.write("\tfloat:right;\r\n");
      out.write("\tmargin-top:20px;\r\n");
      out.write("}\r\n");
      out.write("#v2\r\n");
      out.write("{\r\n");
      out.write("\tfloat:left;\r\n");
      out.write("}\r\n");
      out.write("#v3\r\n");
      out.write("{\r\n");
      out.write("\ttext-align:center;\r\n");
      out.write("\tmargin-top:20px;\r\n");
      out.write("}\r\n");
      out.write(".nav_bar\r\n");
      out.write("{\r\n");
      out.write("background:black;\r\n");
      out.write("border:1px solid #000000;\r\n");
      out.write("width:960px;\r\n");
      out.write("font-weight:bold;\r\n");
      out.write("padding: 10px 50px 10px 20px;\r\n");
      out.write("text-align:center;\r\n");
      out.write("margin-left:170px;\r\n");
      out.write("margin-top:100px;\r\n");
      out.write("margin-right:10px;\r\n");
      out.write("\r\n");
      out.write("height:50px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write(".nav_bar a\r\n");
      out.write("{\r\n");
      out.write("color:white;\r\n");
      out.write("text-decoration:none;\r\n");
      out.write("margin-left:20px;\r\n");
      out.write("margin-right:20px;\r\n");
      out.write("}\r\n");
      out.write(".nav_bar a:hover\r\n");
      out.write("{\r\n");
      out.write(" color:white;\r\n");
      out.write(" text-decoration: underline;\r\n");
      out.write("}\r\n");
      out.write("#carousel1\r\n");
      out.write("{\r\n");
      out.write("\twidth:960px;\r\n");
      out.write("\tmargin-left:170px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("#v4\r\n");
      out.write("{\r\n");
      out.write("\r\n");
      out.write("\twidth:960px;\r\n");
      out.write("\theight:200px;\r\n");
      out.write("\tcolor:black;\r\n");
      out.write("\ttext-align:center;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("#cric\r\n");
      out.write("{\r\n");
      out.write("\twidth:100%;\r\n");
      out.write("\theight:400px;\r\n");
      out.write("\tdisplay:block;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("#cric h2\r\n");
      out.write("{\r\n");
      out.write("\ttext-align:center;\r\n");
      out.write("\tbackground-color:#D3BFBF;\r\n");
      out.write("\twidth:100%;\r\n");
      out.write("\theight:500px;\r\n");
      out.write("}\r\n");
      out.write("#border\r\n");
      out.write("{\r\n");
      out.write("\ttext-align:center;\r\n");
      out.write("\tborder-style: solid;\r\n");
      out.write("\tmargin-left:20px;\r\n");
      out.write("\tmargin-top:10px;\r\n");
      out.write("\tmargin-bottom:10px;\r\n");
      out.write("\tmargin-right:20px;\r\n");
      out.write("\tborder-color:#000000;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write(".img-responsive\r\n");
      out.write(" {\r\n");
      out.write("\tborder-radius:50%;\r\n");
      out.write("}\r\n");
      out.write(".f7\r\n");
      out.write("{\r\n");
      out.write("\twidth:100%;\r\n");
      out.write("\tbackground-color:#2E2C2C;\r\n");
      out.write("\theight:700px;\r\n");
      out.write("\tcolor:#6751A7;\r\n");
      out.write("\tmargin-top:50px;\r\n");
      out.write("\tmargin-left:50px;\r\n");
      out.write("\ttext-align:center;\r\n");
      out.write("\tpadding-top:50px;\r\n");
      out.write("}\r\n");
      out.write(".nav_bar\r\n");
      out.write("{\r\n");
      out.write("background:black;\r\n");
      out.write("border:1px solid #000000;\r\n");
      out.write("width:960px;\r\n");
      out.write("font-weight:bold;\r\n");
      out.write("padding: 10px 50px 10px 20px;\r\n");
      out.write("text-align:center;\r\n");
      out.write("margin-left:170px;\r\n");
      out.write("margin-top:100px;\r\n");
      out.write("margin-right:10px;\r\n");
      out.write("\r\n");
      out.write("height:50px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write(".nav_bar a\r\n");
      out.write("{\r\n");
      out.write("color:white;\r\n");
      out.write("text-decoration:none;\r\n");
      out.write("margin-left:20px;\r\n");
      out.write("margin-right:20px;\r\n");
      out.write("}\r\n");
      out.write(".nav_bar a:hover\r\n");
      out.write("{\r\n");
      out.write(" color:white;\r\n");
      out.write(" text-decoration: underline;\r\n");
      out.write("}\r\n");
      out.write("#login\r\n");
      out.write("{\r\n");
      out.write("\tbackground-color:#9E8383;\r\n");
      out.write("\twidth:700px;\r\n");
      out.write("\theight:500px;\r\n");
      out.write("\tmargin:auto;\r\n");
      out.write("\t\r\n");
      out.write("\ttext-align:center;\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("#login h1\r\n");
      out.write("{\r\n");
      out.write("\ttext-align:center;\r\n");
      out.write("\tpadding-top:40px;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("body\r\n");
      out.write("{\r\n");
      out.write("\r\n");
      out.write("\tbackground-image:url(220483.jpg);\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("#l7\r\n");
      out.write("{\r\n");
      out.write("\tbackground-color:#F4171A;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
